# Generated by Django 4.2.2 on 2024-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_word_conf', models.CharField(max_length=100)),
                ('weightage', models.FloatField(max_length=100)),
                ('about', models.TextField()),
                ('category', models.CharField(choices=[('NDA', 'NDA'), ('SLA', 'SLA')], max_length=100)),
            ],
        ),
    ]
